<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * PaniersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaniersRepository extends \Doctrine\ORM\EntityRepository
{
}
