produits:
    path:     /
    defaults: { _controller: EcommerceBundle:Produits:produits }

presentation:
    path:     /produit/{id}
    defaults: { _controller: EcommerceBundle:Produits:presentation }
    requirements:
        id: '\d+'

panier:
    path:     /panier
    defaults: { _controller: EcommerceBundle:Panier:panier }

adminProduits:
    path:     /admin/produits
    defaults: { _controller: EcommerceBundle:AdminProduits:adminProduits }

categoriesProduits:
    path:     /produits/{categorie}
    defaults: { _controller: EcommerceBundle:Produits:categories }
    requirements:
        categorie: "[a-zA-Z]+"
